experimental = ["setup-scripts"]

[[profile.default.scripts]]
filter = "test(/failpoint_kernel_v5_13_/)"
setup = "failpoint_kernel_v5_13"

[[profile.default.scripts]]
filter = "test(/failpoint_kernel_v5_15_/)"
setup = "failpoint_kernel_v5_15"

[[profile.default.scripts]]
filter = "test(/failpoint_kernel_v5_18_/)"
setup = "failpoint_kernel_v5_18"

[[profile.default.scripts]]
filter = "test(/failpoint_kernel_v5_19_/)"
setup = "failpoint_kernel_v5_19"

[[profile.default.scripts]]
filter = "test(/failpoint_kernel_v6_0_/)"
setup = "failpoint_kernel_v6_0"

[[profile.default.scripts]]
filter = "test(/failpoint_kernel_v6_1_/)"
setup = "failpoint_kernel_v6_1"

[[profile.default.scripts]]
filter = "test(/failpoint_scheduler_run_fail_/)"
setup = "failpoint_scheduler_run_fail"

[[profile.default.scripts]]
filter = "test(/failpoint_scheduler_create_fail_/)"
setup = "failpoint_scheduler_create_fail"

[script.failpoint_kernel_v5_13]
command = ".config/scripts/failpoint_kernel_v5_13.sh"

[script.failpoint_kernel_v5_15]
command = ".config/scripts/failpoint_kernel_v5_15.sh"

[script.failpoint_kernel_v5_18]
command = ".config/scripts/failpoint_kernel_v5_18.sh"

[script.failpoint_kernel_v5_19]
command = ".config/scripts/failpoint_kernel_v5_19.sh"

[script.failpoint_kernel_v6_0]
command = ".config/scripts/failpoint_kernel_v6_0.sh"

[script.failpoint_kernel_v6_1]
command = ".config/scripts/failpoint_kernel_v6_1.sh"

[script.failpoint_scheduler_run_fail]
command = ".config/scripts/failpoint_scheduler_run_fail.sh"

[script.failpoint_scheduler_create_fail]
command = ".config/scripts/failpoint_scheduler_create_fail.sh"